# Generated by Django 6.1 on 2026-09-17 01:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(default='item', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('color', models.CharField(default='#c7bda9', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('item', 'Item'), ('filament', 'Filament')], default='item', max_length=16)),
                ('category', models.CharField(default='Other', max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('min_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('favorite', models.BooleanField(default=False)),
                ('art', models.CharField(choices=[('object', 'object'), ('camera', 'camera'), ('headphones', 'headphones'), ('drill', 'drill'), ('cables', 'cables'), ('tools', 'tools'), ('keyboard', 'keyboard'), ('plant', 'plant'), ('spool', 'spool')], default='object', max_length=20)),
                ('color', models.CharField(default='#9ba89a', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')])),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('material', models.CharField(blank=True, max_length=30)),
                ('total_weight', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('remaining_weight', models.PositiveIntegerField(default=1000)),
                ('low_weight', models.PositiveIntegerField(default=200)),
                ('diameter', models.CharField(choices=[('1.75', '1.75 mm'), ('2.85', '2.85 mm')], default='1.75', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='storeit_app.box')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='storeit_app.location')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='storeit_app.location'),
        ),
    ]
